function [TimeStamp, TimeStampUnix, EXG1CH1] = importfileSynch_v2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIMESTAMP, TIMESTAMPUNIX, EXG2CH2] = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [TIMESTAMP, TIMESTAMPUNIX, EXG2CH2] = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [TimeStamp, TimeStampUnix, EXG2CH2] = importfile("C:\Users\BENCh - Eurobench\Documents\AI4HealthyAging\A53\github_repo_SHIMMER\checksynch3.dat", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jul-2023 13:33:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "TimeStampUnix", "EXG1CH1", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["TimeStamp", "TimeStampUnix", "EXG1CH1"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
TimeStamp = tbl.TimeStamp;
TimeStampUnix = tbl.TimeStampUnix;
EXG1CH1 = tbl.EXG1CH1;
end